# Playbook router
- name: Configuracion de ip_forward e iptables en Kali Linux
  hosts: router
  become: true
  tasks:
    - name: Habilitar el reenvio de IP en /proc/sys/net/ipv4/ip_forward
      sysctl:
        name: net.ipv4.ip_forward
        value: '1'
        state: present
        reload: yes

    - name: Asegurarse de que el reenvio de IP sea persistente
      lineinfile:
        dest: /etc/sysctl.conf
        regexp: '^net.ipv4.ip_forward'
        line: 'net.ipv4.ip_forward = 1'
        state: present

    - name: Instalar iptables-persistent
      apt:
        name: iptables-persistent
        state: present

    - name: Agregar regla de iptables de manera persistente
      iptables:
        table: nat
        chain: POSTROUTING
        out_interface: eth0
        jump: MASQUERADE

    - name: Guardar reglas de iptables en /etc/iptables/rules.v4
      become: true
      shell: iptables-save > /etc/iptables/rules.v4
# Playbook kali
- name: Configuracion de resolv.conf y rc.local en Kali Linux
  hosts: kali
  become: true
  tasks:
    - name: Crear /etc/resolv.conf y agregar nameserver
      copy:
        dest: /etc/resolv.conf
        content: |
          nameserver 10.0.0.250
        owner: root
        group: root
        mode: '0644'

    - name: Crear /etc/rc.local con el contenido especificado
      copy:
        dest: /etc/rc.local
        content: |
          #!/bin/bash
          ip route add 192.168.3.0/24 via 192.168.2.100

          exit 0
        owner: root
        group: root
        mode: '0755'

    - name: Asegurarse de que /etc/rc.local tenga permisos de ejecucion
      file:
        dest: /etc/rc.local
        mode: '0755'
        owner: root
        group: root
        state: file
# Playbook DMZ
- name: Configurar contenedor Web con Docker en DMZ
  hosts: LXC_ub_in_1
  become: true
  tasks:
    - name: Actualizar paquetes del sistema
      apt:
        upgrade: dist
        state: latest
        update_cache: true
        
    - name: Instalar Docker
      apt:
        update_cache: yes
        name: 
          - docker.io
          - python3-pip
          - iptables-persistent
        state: present

    - name: Instalar module Docker en python 
      pip:
        name: docker
        state: present
    
    - name: Instalar versiones especificas de requests y urllib3
      pip:
        name:
          - 'requests<2.29.0'
          - 'urllib3<2.0'
        state: forcereinstall
        executable: pip3

    - name: Habilitar y activar el serivcio Docker
      systemd:
        name: docker
        enabled: yes
        state: started

    - name: Descargar y lanzar el contenedor Docker
      community.docker.docker_container:
        name: juice-shop
        image: bkimminich/juice-shop
        state: started
        ports:
          - "80:3000"
    
    - name: Permitir trafico en el puerto 80 
      iptables: 
        table: filter 
        chain: INPUT 
        protocol: tcp 
        destination_port: 80 
        jump: ACCEPT
        
    - name: Permitir trafico en el puerto 22 
      iptables: 
        table: filter 
        chain: INPUT 
        protocol: tcp 
        destination_port: 22 
        jump: ACCEPT

    - name: Guardar reglas de iptables en /etc/iptables/rules.v4
      become: true
      shell: iptables-save > /etc/iptables/rules.v4